train:
  size: 224
  cuda: 7
  resume: False
  pretrain: True
  mixed_loss: False
  seed: 34718
  lr: 0.001
  batch-size: 32
  img_num: 128
  epochs: 150
  decay: !!float 1e-4
  dataset: isic
  data_path:
  num_worker: 8
  num_classes: 7
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
model:
  folder: checkpoints
  loss_file:
  loss_caller:
  loss_caller_mix:
  alpha: 1.0
  beta: 0.0
  file: resnet
  caller: resnet50
  name: resnet50
  pretrain: resnet50
log:
  folder: logs